In [2]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv('covid_vaccine_statewise.csv')

In [5]:
df.head()

,Updated On,State,Total Doses Administered,Sessions,Sites,First Dose Administered,Second Dose Administered,Male (Doses Administered),Female (Doses Administered),Transgender (Doses Administered),...,18-44 Years (Doses Administered),45-60 Years (Doses Administered),60+ Years (Doses Administered),18-44 Years(Individuals Vaccinated),45-60 Years(Individuals Vaccinated),60+ Years(Individuals Vaccinated),Male(Individuals Vaccinated),Female(Individuals Vaccinated),Transgender(Individuals Vaccinated),Total Individuals Vaccinated
0,16/01/2021,India,48276.0,3455.0,2957.0,48276.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,23757.0,24517.0,2.0,48276.0
1,17/01/2021,India,58604.0,8532.0,4954.0,58604.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,27348.0,31252.0,4.0,58604.0
2,18/01/2021,India,99449.0,13611.0,6583.0,99449.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,41361.0,58083.0,5.0,99449.0
3,19/01/2021,India,195525.0,17855.0,7951.0,195525.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,81901.0,113613.0,11.0,195525.0
4,20/01/2021,India,251280.0,25472.0,10504.0,251280.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,98111.0,153145.0,24.0,251280.0

In [6]:
df.rename(columns={'Updated On' : 'VaccineDate'},inplace=True)

In [7]:
df.head()

,VaccineDate,State,Total Doses Administered,Sessions,Sites,First Dose Administered,Second Dose Administered,Male (Doses Administered),Female (Doses Administered),Transgender (Doses Administered),...,18-44 Years (Doses Administered),45-60 Years (Doses Administered),60+ Years (Doses Administered),18-44 Years(Individuals Vaccinated),45-60 Years(Individuals Vaccinated),60+ Years(Individuals Vaccinated),Male(Individuals Vaccinated),Female(Individuals Vaccinated),Transgender(Individuals Vaccinated),Total Individuals Vaccinated
0,16/01/2021,India,48276.0,3455.0,2957.0,48276.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,23757.0,24517.0,2.0,48276.0
1,17/01/2021,India,58604.0,8532.0,4954.0,58604.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,27348.0,31252.0,4.0,58604.0
2,18/01/2021,India,99449.0,13611.0,6583.0,99449.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,41361.0,58083.0,5.0,99449.0
3,19/01/2021,India,195525.0,17855.0,7951.0,195525.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,81901.0,113613.0,11.0,195525.0
4,20/01/2021,India,251280.0,25472.0,10504.0,251280.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,98111.0,153145.0,24.0,251280.0

In [8]:
df.isnull().sum()

VaccineDate                               0
State                                     0
Total Doses Administered                224
Sessions                                224
 Sites                                  224
First Dose Administered                 224
Second Dose Administered                224
Male (Doses Administered)               384
Female (Doses Administered)             384
Transgender (Doses Administered)        384
 Covaxin (Doses Administered)           224
CoviShield (Doses Administered)         224
Sputnik V (Doses Administered)         4850
AEFI                                   2407
18-44 Years (Doses Administered)       6143
45-60 Years (Doses Administered)       6143
60+ Years (Doses Administered)         6143
18-44 Years(Individuals Vaccinated)    4112
45-60 Years(Individuals Vaccinated)    4111
60+ Years(Individuals Vaccinated)      4111
Male(Individuals Vaccinated)           7685
Female(Individuals Vaccinated)         7685
Transgender(Individuals Vaccinated)    7685
Total Individuals Vaccinated           1926
dtype: int64

In [9]:
df=df.drop(columns=['Sputnik V (Doses Administered)','AEFI','18-44 Years (Doses Administered)','45-60 Years (Doses Administered)','60+ Years (Doses Administered)'],axis=1)

In [10]:
df

,VaccineDate,State,Total Doses Administered,Sessions,Sites,First Dose Administered,Second Dose Administered,Male (Doses Administered),Female (Doses Administered),Transgender (Doses Administered),Covaxin (Doses Administered),CoviShield (Doses Administered),18-44 Years(Individuals Vaccinated),45-60 Years(Individuals Vaccinated),60+ Years(Individuals Vaccinated),Male(Individuals Vaccinated),Female(Individuals Vaccinated),Transgender(Individuals Vaccinated),Total Individuals Vaccinated
0,16/01/2021,India,48276.0,3455.0,2957.0,48276.0,0.0,NaN,NaN,NaN,579.0,47697.0,NaN,NaN,NaN,23757.0,24517.0,2.0,48276.0
1,17/01/2021,India,58604.0,8532.0,4954.0,58604.0,0.0,NaN,NaN,NaN,635.0,57969.0,NaN,NaN,NaN,27348.0,31252.0,4.0,58604.0
2,18/01/2021,India,99449.0,13611.0,6583.0,99449.0,0.0,NaN,NaN,NaN,1299.0,98150.0,NaN,NaN,NaN,41361.0,58083.0,5.0,99449.0
3,19/01/2021,India,195525.0,17855.0,7951.0,195525.0,0.0,NaN,NaN,NaN,3017.0,192508.0,NaN,NaN,NaN,81901.0,113613.0,11.0,195525.0
4,20/01/2021,India,251280.0,25472.0,10504.0,251280.0,0.0,NaN,NaN,NaN,3946.0,247334.0,NaN,NaN,NaN,98111.0,153145.0,24.0,251280.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7840,11/08/2021,West Bengal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7841,12/08/2021,West Bengal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7842,13/08/2021,West Bengal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7843,14/08/2021,West Bengal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7844,15/08/2021,West Bengal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df.isnull().sum()

VaccineDate                               0
State                                     0
Total Doses Administered                224
Sessions                                224
 Sites                                  224
First Dose Administered                 224
Second Dose Administered                224
Male (Doses Administered)               384
Female (Doses Administered)             384
Transgender (Doses Administered)        384
 Covaxin (Doses Administered)           224
CoviShield (Doses Administered)         224
18-44 Years(Individuals Vaccinated)    4112
45-60 Years(Individuals Vaccinated)    4111
60+ Years(Individuals Vaccinated)      4111
Male(Individuals Vaccinated)           7685
Female(Individuals Vaccinated)         7685
Transgender(Individuals Vaccinated)    7685
Total Individuals Vaccinated           1926
dtype: int64

In [12]:
perc = 75.0 # Here N is 75
min_count =  int(((100-perc)/100)*df.shape[1] + 1)
mod_df = df.dropna( axis=0, 
                    thresh=min_count)

In [13]:
mod_df.tail()

,VaccineDate,State,Total Doses Administered,Sessions,Sites,First Dose Administered,Second Dose Administered,Male (Doses Administered),Female (Doses Administered),Transgender (Doses Administered),Covaxin (Doses Administered),CoviShield (Doses Administered),18-44 Years(Individuals Vaccinated),45-60 Years(Individuals Vaccinated),60+ Years(Individuals Vaccinated),Male(Individuals Vaccinated),Female(Individuals Vaccinated),Transgender(Individuals Vaccinated),Total Individuals Vaccinated
7834,05/08/2021,West Bengal,31371174.0,1018095.0,2604.0,22401043.0,8970131.0,16767671.0,14598799.0,4704.0,3868710.0,27463266.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7835,06/08/2021,West Bengal,31774086.0,930084.0,2485.0,22745949.0,9028137.0,16949389.0,14819919.0,4778.0,3990579.0,27743329.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7836,07/08/2021,West Bengal,32029325.0,727057.0,1833.0,22959053.0,9070272.0,17066449.0,14958036.0,4840.0,4077069.0,27910835.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7837,08/08/2021,West Bengal,32098768.0,271684.0,584.0,23017864.0,9080904.0,17098464.0,14995446.0,4858.0,4091163.0,27965147.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7838,09/08/2021,West Bengal,32390378.0,866173.0,2086.0,23257417.0,9132961.0,17234284.0,15151152.0,4942.0,4168230.0,28178632.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
mod_df.isnull().sum()

VaccineDate                               0
State                                     0
Total Doses Administered                  0
Sessions                                  0
 Sites                                    0
First Dose Administered                   0
Second Dose Administered                  0
Male (Doses Administered)               160
Female (Doses Administered)             160
Transgender (Doses Administered)        160
 Covaxin (Doses Administered)             0
CoviShield (Doses Administered)           0
18-44 Years(Individuals Vaccinated)    3888
45-60 Years(Individuals Vaccinated)    3887
60+ Years(Individuals Vaccinated)      3887
Male(Individuals Vaccinated)           7461
Female(Individuals Vaccinated)         7461
Transgender(Individuals Vaccinated)    7461
Total Individuals Vaccinated           1702
dtype: int64

In [15]:
perc = 80.0 # Here N is 75
min_count =  int(((100-perc)/100)*df.shape[0] + 1)
data = mod_df.dropna( axis=1, 
                    thresh=min_count)

In [16]:
data.isnull().sum()

VaccineDate                               0
State                                     0
Total Doses Administered                  0
Sessions                                  0
 Sites                                    0
First Dose Administered                   0
Second Dose Administered                  0
Male (Doses Administered)               160
Female (Doses Administered)             160
Transgender (Doses Administered)        160
 Covaxin (Doses Administered)             0
CoviShield (Doses Administered)           0
18-44 Years(Individuals Vaccinated)    3888
45-60 Years(Individuals Vaccinated)    3887
60+ Years(Individuals Vaccinated)      3887
Total Individuals Vaccinated           1702
dtype: int64

In [17]:
data.head()

,VaccineDate,State,Total Doses Administered,Sessions,Sites,First Dose Administered,Second Dose Administered,Male (Doses Administered),Female (Doses Administered),Transgender (Doses Administered),Covaxin (Doses Administered),CoviShield (Doses Administered),18-44 Years(Individuals Vaccinated),45-60 Years(Individuals Vaccinated),60+ Years(Individuals Vaccinated),Total Individuals Vaccinated
0,16/01/2021,India,48276.0,3455.0,2957.0,48276.0,0.0,NaN,NaN,NaN,579.0,47697.0,NaN,NaN,NaN,48276.0
1,17/01/2021,India,58604.0,8532.0,4954.0,58604.0,0.0,NaN,NaN,NaN,635.0,57969.0,NaN,NaN,NaN,58604.0
2,18/01/2021,India,99449.0,13611.0,6583.0,99449.0,0.0,NaN,NaN,NaN,1299.0,98150.0,NaN,NaN,NaN,99449.0
3,19/01/2021,India,195525.0,17855.0,7951.0,195525.0,0.0,NaN,NaN,NaN,3017.0,192508.0,NaN,NaN,NaN,195525.0
4,20/01/2021,India,251280.0,25472.0,10504.0,251280.0,0.0,NaN,NaN,NaN,3946.0,247334.0,NaN,NaN,NaN,251280.0

In [18]:
data=data[data.State!='India']

In [19]:
data.isnull().sum()

VaccineDate                               0
State                                     0
Total Doses Administered                  0
Sessions                                  0
 Sites                                    0
First Dose Administered                   0
Second Dose Administered                  0
Male (Doses Administered)                 0
Female (Doses Administered)               0
Transgender (Doses Administered)          0
 Covaxin (Doses Administered)             0
CoviShield (Doses Administered)           0
18-44 Years(Individuals Vaccinated)    3783
45-60 Years(Individuals Vaccinated)    3782
60+ Years(Individuals Vaccinated)      3782
Total Individuals Vaccinated           1656
dtype: int64

In [20]:
data

,VaccineDate,State,Total Doses Administered,Sessions,Sites,First Dose Administered,Second Dose Administered,Male (Doses Administered),Female (Doses Administered),Transgender (Doses Administered),Covaxin (Doses Administered),CoviShield (Doses Administered),18-44 Years(Individuals Vaccinated),45-60 Years(Individuals Vaccinated),60+ Years(Individuals Vaccinated),Total Individuals Vaccinated
212,16/01/2021,Andaman and Nicobar Islands,23.0,2.0,2.0,23.0,0.0,12.0,11.0,0.0,0.0,23.0,NaN,NaN,NaN,23.0
213,17/01/2021,Andaman and Nicobar Islands,23.0,2.0,2.0,23.0,0.0,12.0,11.0,0.0,0.0,23.0,NaN,NaN,NaN,23.0
214,18/01/2021,Andaman and Nicobar Islands,42.0,9.0,2.0,42.0,0.0,29.0,13.0,0.0,0.0,42.0,NaN,NaN,NaN,42.0
215,19/01/2021,Andaman and Nicobar Islands,89.0,12.0,2.0,89.0,0.0,53.0,36.0,0.0,0.0,89.0,NaN,NaN,NaN,89.0
216,20/01/2021,Andaman and Nicobar Islands,124.0,16.0,3.0,124.0,0.0,67.0,57.0,0.0,0.0,124.0,NaN,NaN,NaN,124.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7834,05/08/2021,West Bengal,31371174.0,1018095.0,2604.0,22401043.0,8970131.0,16767671.0,14598799.0,4704.0,3868710.0,27463266.0,NaN,NaN,NaN,NaN
7835,06/08/2021,West Bengal,31774086.0,930084.0,2485.0,22745949.0,9028137.0,16949389.0,14819919.0,4778.0,3990579.0,27743329.0,NaN,NaN,NaN,NaN
7836,07/08/2021,West Bengal,32029325.0,727057.0,1833.0,22959053.0,9070272.0,17066449.0,14958036.0,4840.0,4077069.0,27910835.0,NaN,NaN,NaN,NaN
7837,08/08/2021,West Bengal,32098768.0,271684.0,584.0,23017864.0,9080904.0,17098464.0,14995446.0,4858.0,4091163.0,27965147.0,NaN,NaN,NaN,NaN
7838,09/08/2021,West Bengal,32390378.0,866173.0,2086.0,23257417.0,9132961.0,17234284.0,15151152.0,4942.0,4168230.0,28178632.0,NaN,NaN,NaN,NaN

In [21]:
data=data.fillna(0)

In [22]:
data

,VaccineDate,State,Total Doses Administered,Sessions,Sites,First Dose Administered,Second Dose Administered,Male (Doses Administered),Female (Doses Administered),Transgender (Doses Administered),Covaxin (Doses Administered),CoviShield (Doses Administered),18-44 Years(Individuals Vaccinated),45-60 Years(Individuals Vaccinated),60+ Years(Individuals Vaccinated),Total Individuals Vaccinated
212,16/01/2021,Andaman and Nicobar Islands,23.0,2.0,2.0,23.0,0.0,12.0,11.0,0.0,0.0,23.0,0.0,0.0,0.0,23.0
213,17/01/2021,Andaman and Nicobar Islands,23.0,2.0,2.0,23.0,0.0,12.0,11.0,0.0,0.0,23.0,0.0,0.0,0.0,23.0
214,18/01/2021,Andaman and Nicobar Islands,42.0,9.0,2.0,42.0,0.0,29.0,13.0,0.0,0.0,42.0,0.0,0.0,0.0,42.0
215,19/01/2021,Andaman and Nicobar Islands,89.0,12.0,2.0,89.0,0.0,53.0,36.0,0.0,0.0,89.0,0.0,0.0,0.0,89.0
216,20/01/2021,Andaman and Nicobar Islands,124.0,16.0,3.0,124.0,0.0,67.0,57.0,0.0,0.0,124.0,0.0,0.0,0.0,124.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7834,05/08/2021,West Bengal,31371174.0,1018095.0,2604.0,22401043.0,8970131.0,16767671.0,14598799.0,4704.0,3868710.0,27463266.0,0.0,0.0,0.0,0.0
7835,06/08/2021,West Bengal,31774086.0,930084.0,2485.0,22745949.0,9028137.0,16949389.0,14819919.0,4778.0,3990579.0,27743329.0,0.0,0.0,0.0,0.0
7836,07/08/2021,West Bengal,32029325.0,727057.0,1833.0,22959053.0,9070272.0,17066449.0,14958036.0,4840.0,4077069.0,27910835.0,0.0,0.0,0.0,0.0
7837,08/08/2021,West Bengal,32098768.0,271684.0,584.0,23017864.0,9080904.0,17098464.0,14995446.0,4858.0,4091163.0,27965147.0,0.0,0.0,0.0,0.0
7838,09/08/2021,West Bengal,32390378.0,866173.0,2086.0,23257417.0,9132961.0,17234284.0,15151152.0,4942.0,4168230.0,28178632.0,0.0,0.0,0.0,0.0

In [24]:
data['VaccineDate'] = pd. to_datetime(data['VaccineDate'],format='%d/%m/%Y')
data['year'] = pd. DatetimeIndex(data['VaccineDate']). year
data['month'] = pd. DatetimeIndex(data['VaccineDate']). month

In [25]:
data.head()

,VaccineDate,State,Total Doses Administered,Sessions,Sites,First Dose Administered,Second Dose Administered,Male (Doses Administered),Female (Doses Administered),Transgender (Doses Administered),Covaxin (Doses Administered),CoviShield (Doses Administered),18-44 Years(Individuals Vaccinated),45-60 Years(Individuals Vaccinated),60+ Years(Individuals Vaccinated),Total Individuals Vaccinated,year,month
212,2021-01-16,Andaman and Nicobar Islands,23.0,2.0,2.0,23.0,0.0,12.0,11.0,0.0,0.0,23.0,0.0,0.0,0.0,23.0,2021,1
213,2021-01-17,Andaman and Nicobar Islands,23.0,2.0,2.0,23.0,0.0,12.0,11.0,0.0,0.0,23.0,0.0,0.0,0.0,23.0,2021,1
214,2021-01-18,Andaman and Nicobar Islands,42.0,9.0,2.0,42.0,0.0,29.0,13.0,0.0,0.0,42.0,0.0,0.0,0.0,42.0,2021,1
215,2021-01-19,Andaman and Nicobar Islands,89.0,12.0,2.0,89.0,0.0,53.0,36.0,0.0,0.0,89.0,0.0,0.0,0.0,89.0,2021,1
216,2021-01-20,Andaman and Nicobar Islands,124.0,16.0,3.0,124.0,0.0,67.0,57.0,0.0,0.0,124.0,0.0,0.0,0.0,124.0,2021,1

In [26]:
d={1:'January',2:'February',3:'March',4:'April',5:'May',6:'June',7:'July',8:'August',9:'September',10:'October',11:'November',12:'December'}
data.month=data.month.map(d)

In [27]:
data.head()

,VaccineDate,State,Total Doses Administered,Sessions,Sites,First Dose Administered,Second Dose Administered,Male (Doses Administered),Female (Doses Administered),Transgender (Doses Administered),Covaxin (Doses Administered),CoviShield (Doses Administered),18-44 Years(Individuals Vaccinated),45-60 Years(Individuals Vaccinated),60+ Years(Individuals Vaccinated),Total Individuals Vaccinated,year,month
212,2021-01-16,Andaman and Nicobar Islands,23.0,2.0,2.0,23.0,0.0,12.0,11.0,0.0,0.0,23.0,0.0,0.0,0.0,23.0,2021,January
213,2021-01-17,Andaman and Nicobar Islands,23.0,2.0,2.0,23.0,0.0,12.0,11.0,0.0,0.0,23.0,0.0,0.0,0.0,23.0,2021,January
214,2021-01-18,Andaman and Nicobar Islands,42.0,9.0,2.0,42.0,0.0,29.0,13.0,0.0,0.0,42.0,0.0,0.0,0.0,42.0,2021,January
215,2021-01-19,Andaman and Nicobar Islands,89.0,12.0,2.0,89.0,0.0,53.0,36.0,0.0,0.0,89.0,0.0,0.0,0.0,89.0,2021,January
216,2021-01-20,Andaman and Nicobar Islands,124.0,16.0,3.0,124.0,0.0,67.0,57.0,0.0,0.0,124.0,0.0,0.0,0.0,124.0,2021,January

In [30]:
data.to_excel('vaccination.xlsx', index=False)